services:
  - type: web
    name: project_management
    env: docker
    buildCommand: docker build -t project_management .
    startCommand: docker run -p $PORT:80 -e PORT=$PORT -e APP_KEY -e APP_URL -e DB_HOST -e DB_DATABASE -e DB_USERNAME -e DB_PASSWORD -e MAIL_HOST -e MAIL_USERNAME -e MAIL_PASSWORD -e MAIL_FROM_ADDRESS project_management
    healthCheckPath: /login
    healthCheckTimeout: 100
    autoDeploy: true
    envVars:
      - key: APP_KEY
        generateValue: true # This will generate a random 32-character key
    envVars:
      - key: APP_NAME
        value: Worksuite
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: project_management
          type: web
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: HOST_URL # Replace with your actual database host
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: your_database_name
      - key: DB_USERNAME
        value: your_database_username
      - key: DB_PASSWORD
        sync: false # This will prompt you to enter the value in Render dashboard
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: your_smtp_host
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: your_from_email
      - key: MAIL_FROM_NAME
        value: "${APP_NAME}"
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: MOLLIE_KEY
        sync: false
